package codegen

import (
	"github.com/dave/jennifer/jen"

	"github.com/srdtrk/go-codegen/pkg/schemas"
)

func GenerateCodeFromIDLSchema(idlSchema *schemas.IDLSchema, outputPath string) error {
	if idlSchema == nil {
		panic("idlSchema is nil")
	}

	f := jen.NewFile("main")
	f.PackageComment("Code generated by github.com/srdtrk/go-codegen, DO NOT EDIT.")

	if idlSchema.Instantiate == nil {
		panic("no InstantiateMsg schema")
	}

	GenerateInstantiateMsg(f, idlSchema.Instantiate)
	GenerateExecuteMsg(f, idlSchema.Execute)
	GenerateSudoMsg(f, idlSchema.Sudo)
	GenerateMigrateMsg(f, idlSchema.Migrate)
	GenerateQueryMsg(f, idlSchema.Query)
	GenerateResponses(f, idlSchema.Responses)

	generateDefinitions(f)

	if err := f.Save(outputPath); err != nil {
		return err
	}

	return nil
}
