package codegen

import (
	"github.com/dave/jennifer/jen"

	"github.com/srdtrk/go-codegen/pkg/schemas"
)

func GenerateCodeFromIDLSchema(idlSchema *schemas.IDLSchema, outputPath string) error {
	if idlSchema == nil {
		panic("idlSchema is nil")
	}

	f := jen.NewFile("main")
	f.PackageComment("Code generated by github.com/srdtrk/go-codegen, DO NOT EDIT.")
	GenerateInstantiateMsg(f, idlSchema.Instantiate)
	GenerateExecuteMsg(f, idlSchema.Execute)

	generateDefinitions(f)

	if err := f.Save(outputPath); err != nil {
		return err
	}

	return nil
}
