name: integration-tests
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/integration.yml'
      - '**.plush'
permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        test:
          # List your tests here
          - TestWithMySuite/TestMessageComposer
          - TestWithMySuite/TestInterchaintestScaffold
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54
          args: --timeout 5m
          working-directory: integration_test
      - name: Build
        run: make build
      - name: Run Tests
        run: |
          cd integration_test
          go test -v -mod=readonly . -run=${{ matrix.test }}
